name: nodeJS Pipeline
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Create folder
        run: mkdir -p siyam

      - name:   Create a file in the folder
        run: echo "This file was created by CI" > siyam/info.txt



  